#13 - Go
mouredev/roadmap-retos-programacion pull request #2609
Opened 2024-03-28 19:59 UTC by hozlucas28

## Describe tus cambios
***(Opcional)*** *Sobre todo aconsejable si la "Pull Request" se corresponde con una corrección adicional y no con la presentación de un ejercicio.*

## Comprobaciones
Asegúrate de cumplir los siguientes puntos antes de realizar la "Pull Request":

- [ ] El título de mi Pull Request sigue este formato: "#[número] - [lenguaje_utilizado]". *(Ej: #00 - Python")*
- [ ] El nombre el fichero que se corresponde con el de mi usuario en GitHub más la extensión del lenguaje. *(Ej: mouredev.py)*
- [ ] El fichero de corrección se encuentra dentro del directorio del ejercicio y en una carpeta con el nombre del lenguaje de programación utilizado en minúsculas. *(Ej: 00/python/mouredev.py)*
- [ ] He revisado que el nombre del directorio del lenguaje no es conflictivo:
	- c#, no csharp
	- c++, no cplusplus
	- go, no golang
	- javascript, no js
- [ ] Únicamente he incluido los ficheros de ejercicios. No se aceptarán Pull Requests que contengan archivos adicionales asociados a editores de código o semejantes.

## Información

* Tienes toda la información sobre los retos semanales en [retosdeprogramacion.com/roadmap](https://retosdeprogramacion.com/roadmap).
* Cada semana se realizará la corrección en directo y publicación de un nuevo reto en [twitch.tv/mouredev](https://twitch.tv/mouredev).
* Recuerda que tienes un grupo de apoyo llamado "reto-semanal" en [Discord](https://discord.gg/mouredev).

2024-03-28 20:05 UTC, hozlucas28 commented
No pude incorporar los Test's, presentes en el archivo [hozlucas28_test.go](https://github.com/mouredev/roadmap-retos-programacion/pull/2609/files#diff-0ec8ba4d4564ad15062231f6e1b08c88debb0f141f25a8021e725eacbaba3d9d), al archivo [hozlucas28.go](https://github.com/mouredev/roadmap-retos-programacion/pull/2609/files#diff-f323ba39e7b37c70182f35856349c9530bc4c099eacf0210881d2eb648edc100). Por lo que leí en la documentación de Go, los Test's deben estar en un archivo separado que finalize con `*_test.go` para que el compilador los detecte y los ejecute al ingresar por consola el comando `go test`.

2024-03-29 12:50 UTC, Roswell468 requested changes
Por favor incluye todo en un solo archivo, independientemente de que no se pueda ejecutar.
La finalidad del repo es que la gente pueda ver el código y la lógica de programación. 
Luego cada uno verá, si quiere ejecutarlo, lo que tenga que hacer para poder hacerlo.
Deja como comentario en el código lo que indicas en la PR y coloca todo en un mismo archivo.
Gracias.
Saludos.

2024-03-29 15:46 UTC, hozlucas28 commented
Listo, combine los dos archivos (`hozlucas28_test.go` -> `hozlucas28.go`) y agregue un comentario indicando los cambios que se deben hacer para poder ejecutar exitosamente los Tests.

2024-03-30 20:46 UTC, Roswell468 approved these changes

2024-03-30 20:46 UTC, merged