#02 - Python
mouredev/roadmap-retos-programacion pull request #3244
Opened 2024-04-28 10:42 UTC by ChristianCoC

Solución al reto #02 Python.

2024-04-29 08:05 UTC, kontroldev requested changes
Hola! Por favor revisa las [reglas](https://github.com/mouredev/roadmap-retos-programacion#instrucciones) de aportación de ejercicios.

-No puedes modificar los ficheros de otros usuarios. Por favor revierte esos cambios.

2024-05-03 14:00 UTC, ChristianCoC commented
Ya reverti el cambio, no se que pudo haber modificado el nombre de ese archivo.

2024-05-06 00:19 UTC, ChristianCoC commented
Solución ejercicio #03 Python.

2024-05-08 07:27 UTC, kontroldev commented
-No puedes modificar los ficheros de otros usuarios. Por favor revierte esos cambios.

<img width="341" alt="Captura de pantalla 2024-05-08 a las 9 26 40" src="https://github.com/mouredev/roadmap-retos-programacion/assets/75795616/7617982c-da5a-4eb5-b68f-96a235e4bcb4">

2024-05-14 10:22 UTC, kontroldev commented
Hola,

Se cierramos PR por inactividad. Puedes enviar una nueva cuando quieras. Recuerda revisar reglas y comentarios.

Muchas gracias.

2024-05-14 10:22 UTC, closed without merging