Reto #00 java
mouredev/roadmap-retos-programacion pull request #33
Opened 2023-12-27 00:41 UTC by CarlosRinconsofdev

## Describe tus cambios
***(Opcional)*** *Sobre todo aconsejable si la "Pull Request" se corresponde con una corrección adicional y no con la presentación de un ejercicio.*

## Comprobaciones
Asegúrate de cumplir los siguientes puntos antes de realizar la "Pull Request":

- [ ] El título de mi Pull Request sigue este formato: "#[número] - [lenguaje_utilizado]". *(Ej: #00 - Python")*
- [ ] El nombre el fichero que se corresponde con el de mi usuario en GitHub más la extensión del lenguaje. *(Ej: mouredev.py)*
- [ ] El fichero de corrección se encuentra dentro del directorio del ejercicio y en una carpeta con el nombre del lenguaje de programación utilizado en minúsculas. *(Ej: 00/python/mouredev.py)*
- [ ] He revisado que el nombre del directorio del lenguaje no es conflictivo:
	- c#, no csharp
	- c++, no cplusplus
	- go, no golang
	- javascript, no js
- [ ] Únicamente he incluído los ficheros de ejercicios. No se aceptarán Pull Requests que contengan archivos adicionales asociados a editores de código o semejantes.

## Información

* Tienes toda la información sobre los retos semanales en [retosdeprogramacion.com/roadmap](https://retosdeprogramacion.com/roadmap).
* Cada semana se realizará la corrección en directo y publicación de un nuevo reto en [twitch.tv/mouredev](https://twitch.tv/mouredev).
* Recuerda que tienes un grupo de apoyo llamado "reto-semanal" en [Discord](https://discord.gg/mouredev).

2023-12-27 00:43 UTC, CarlosRinconsofdev commented
El pull request cumple con todos los aspectos requeridos para ser solicitado.

2023-12-27 16:43 UTC, CarlosRinconsofdev reviewed
It's ok

2023-12-28 00:01 UTC, Roswell468 requested changes
Hola! Por favor revisa las  [reglas](https://github.com/mouredev/roadmap-retos-programacion#instrucciones) de aportación de ejercicios.

- El nombre del fichero debe coincidir con el de tu usuario en GitHub más la extensión del lenguaje. (Ej: mouredev.py)

Gracias.
Saludos.

2024-01-08 07:44 UTC, mouredev commented
Hola,

Se cierra PR por inactividad. Puedes enviar una nueva cuando quieras. Recuerda revisar reglas y comentarios.

Muchas gracias.

2024-01-08 07:44 UTC, closed without merging