#03 - Python
mouredev/roadmap-retos-programacion pull request #4669
Opened 2024-07-01 00:35 UTC by sunjamer

## añadir sunjamer.py #03 - Python

***(Opcional)*** *Sobre todo aconsejable si la "Pull Request" se corresponde con una corrección adicional y no con la presentación de un ejercicio.*

## Comprobaciones
Asegúrate de cumplir los siguientes puntos antes de realizar la "Pull Request":

- [x] El título de mi Pull Request sigue este formato: "#[número] - [lenguaje_utilizado]". *(Ej: #00 - Python")*
- [x] El nombre el fichero que se corresponde con el de mi usuario en GitHub más la extensión del lenguaje. *(Ej: mouredev.py)*
- [x] El fichero de corrección se encuentra dentro del directorio del ejercicio y en una carpeta con el nombre del lenguaje de programación utilizado en minúsculas. *(Ej: 00/python/mouredev.py)*
- [x] He revisado que el nombre del directorio del lenguaje no es conflictivo:
	- c#, no csharp
	- c++, no cplusplus
	- go, no golang
	- javascript, no js
- [x] Únicamente he incluido los ficheros de ejercicios. No se aceptarán Pull Requests que contengan archivos adicionales asociados a editores de código o semejantes.

## Información

* Tienes toda la información sobre los retos semanales en [retosdeprogramacion.com/roadmap](https://retosdeprogramacion.com/roadmap).
* Cada semana se realizará la corrección en directo y publicación de un nuevo reto en [twitch.tv/mouredev](https://twitch.tv/mouredev).
* Recuerda que tienes un grupo de apoyo llamado "reto-semanal" en [Discord](https://discord.gg/mouredev).

2024-07-02 09:18 UTC, kontroldev requested changes
Hola! Por favor revisa las [reglas](https://github.com/mouredev/roadmap-retos-programacion#instrucciones) de aportación de ejercicios.

-No puedes modificar los ficheros de otros usuarios. Por favor revierte esos cambios.

2024-07-02 09:51 UTC, kontroldev commented
Pedro, si necesitas ayuda?, 
Estoy ahora por Discord y te ayudo.

2024-07-02 11:51 UTC, kontroldev commented
NO te preocupes, si esta noche cuando te pongas, me ves conectado, avísame y te ayudo.

2024-07-02 21:29 UTC, sunjamer commented
Hola, no consigo que los ficheros de **saicobys.py** del reto #00 - python y del reto #01 - python que estan en el repo de mouredev aparezcan en mi repo que tengo forkeado con el de mouredev,  Y por tanto tampoco me los puedo traer a mi local. Y he hecho sync fork un montón de veces... supongo que por eso al hacer las pull request parece que estoy intentando borrar estos dos ficheros.

2024-07-04 01:45 UTC, sunjamer commented
revisando los commits veo que el commit [321ee55](https://github.com/mouredev/roadmap-retos-programacion/pull/4669/commits/321ee55ad434dcd1a3b4c8b341e7575e681b2958)  cuando hago sync fork y lo bajo a mi repositorio local es cuando me hace desaparecer los dos ficheros del usuario saicobys (saicobys.py) y a partir de ese momento, aunque haga sync fork no me vuelven a aparecer en mi fork ni en mi local y cualquier pull request que hago siempre me dice que voy a eliminar los ficheros de ese usuario.  Y no se como recuperar un estado en que tenga esos ficheros de nuevo en mi repositorio local

2024-07-04 08:45 UTC, kontroldev commented
Mira eś mas fácil lo que crees.
-TUS dos ejercicios que tienes hecho, los pones en el escritorio.
-El repo que tienes en local(en tu PC) eliminas todas las carpetas(eliminas todo el repo) y luego lo vuelves a clonar de nuevo a tu maquina.
- Trasladas los dos ejercicios que pusiste al principio en el escritorio en las carpetas correspondientes.
Y haces un git add.. y veras que solo tendrás dos cambios, los dos ejercicios que has añadido antes y lo subes.
- Una vez hecho el push, tienes que irte a tu repo y enviar la PR al repo de Moure y listo.

Es fácil y repito, no te preocupes en probar cosas, no se van a romper nada si mis compañeros no aceptados nada, no pasara nada.

Rompe, borra, vuelve a crear todo lo que tu veas necesario, por que de los errores, también aprendemos.

2024-07-04 11:34 UTC, sunjamer commented
> Mira eś mas fácil lo que crees. -TUS dos ejercicios que tienes hecho, los pones en el escritorio. -El repo que tienes en local(en tu PC) eliminas todas las carpetas(eliminas todo el repo) y luego lo vuelves a clonar de nuevo a tu maquina.
> 
> * Trasladas los dos ejercicios que pusiste al principio en el escritorio en las carpetas correspondientes.
>   Y haces un git add.. y veras que solo tendrás dos cambios, los dos ejercicios que has añadido antes y lo subes.
> * Una vez hecho el push, tienes que irte a tu repo y enviar la PR al repo de Moure y listo.
> 
> Es fácil y repito, no te preocupes en probar cosas, no se van a romper nada si mis compañeros no aceptados nada, no pasara nada.
> 
> Rompe, borra, vuelve a crear todo lo que tu veas necesario, por que de los errores, también aprendemos.
> 
> esto ultimo te lo puede decir Roswell468, que al principio le enviaba de todo en las PR, hasta las fotos de mi primera comunión y todo. 😅🫣

Muchas gracias! Esta noche intento hacer lo que dices. 

un saludo!

2024-07-05 01:12 UTC, Roswell468 commented
Yo hice lo que dice Kontrol. Borré y cloné de nuevo porque tampoco lo podía arreglar esos archivos 😂🤣

2024-07-15 10:04 UTC, kontroldev commented
Hola,

Cerramos PR por inactividad. Puedes enviar una nueva cuando quieras. Recuerda revisar reglas y comentarios.

Muchas gracias.

2024-07-15 10:04 UTC, closed without merging