Create dannett7.py
mouredev/roadmap-retos-programacion pull request #5188
Opened 2024-07-30 00:15 UTC by Dannett7

## Describe tus cambios
***(Opcional)*** *Sobre todo aconsejable si la "Pull Request" se corresponde con una corrección adicional y no con la presentación de un ejercicio.*

## Comprobaciones
Asegúrate de cumplir los siguientes puntos antes de realizar la "Pull Request":

- [ ] El título de mi Pull Request sigue este formato: "#[número] - [lenguaje_utilizado]". *(Ej: #00 - Python")*
- [ ] El nombre el fichero que se corresponde con el de mi usuario en GitHub más la extensión del lenguaje. *(Ej: mouredev.py)*
- [ ] El fichero de corrección se encuentra dentro del directorio del ejercicio y en una carpeta con el nombre del lenguaje de programación utilizado en minúsculas. *(Ej: 00/python/mouredev.py)*
- [ ] He revisado que el nombre del directorio del lenguaje no es conflictivo:
	- c#, no csharp
	- c++, no cplusplus
	- go, no golang
	- javascript, no js
- [ ] Únicamente he incluido los ficheros de ejercicios. No se aceptarán Pull Requests que contengan archivos adicionales asociados a editores de código o semejantes.

## Información

* Tienes toda la información sobre los retos semanales en [retosdeprogramacion.com/roadmap](https://retosdeprogramacion.com/roadmap).
* Cada semana se realizará la corrección en directo y publicación de un nuevo reto en [twitch.tv/mouredev](https://twitch.tv/mouredev).
* Recuerda que tienes un grupo de apoyo llamado "reto-semanal" en [Discord](https://discord.gg/mouredev).

2024-07-31 08:09 UTC, kontroldev requested changes
No enviaste código....

2024-07-31 20:04 UTC, Dannett7 commented
Hola Raúl es que tuve problema para empezar, será que tengo que aprender el
video tutorial de como usar Gitlab, el que dura 5 horas? Ese es pre
requisito para poder empezar el de lógica? Muchas gracias por tu tiempo!

El mié, 31 jul 2024 a las 2:10, Raúl Gallego ***@***.***>)
escribió:

> ***@***.**** requested changes on this pull request.
>
> No enviaste código....
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mouredev/roadmap-retos-programacion/pull/5188#pullrequestreview-2209471476>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQINPZ2U5Y6NJFYGNA6RL2TZPCLWXAVCNFSM6AAAAABLVIVLZWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMBZGQ3TCNBXGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2024-08-01 09:17 UTC, kontroldev commented
Buenas Dannet.
Tienes varias recursos, puedes hacer el curso de Moure -> https://github.com/mouredev/hello-git
Y también tienes varios grupo en Discord para poder preguntar, el canal de git-github o un grupo de estudio -> https://discord.com/channels/729672926432985098/1221229403347095632

O si no lo tienes claro. llámame por algún canal y te ayudo.
Que hacemos con la PR, la cerramos o intentamos subir el ejercicio..? (yo te ayudo si quieres)

2024-08-13 09:37 UTC, kontroldev commented
Hola,

Cerramos PR por inactividad. Puedes enviar una nueva cuando quieras. Recuerda revisar reglas y comentarios.

Muchas gracias

2024-08-13 09:37 UTC, closed without merging