#00 - Java
mouredev/roadmap-retos-programacion pull request #59
Opened 2023-12-27 13:31 UTC by josetomas09

2023-12-27 23:44 UTC, Roswell468 requested changes
Hola! Revisa nuevamente la PR.
Has creado una nueva Pull Request con el nombre corregido,  pero incluye la solución anterior (con el nombre incorrecto).
Gracias.
Saludos.

2023-12-28 04:15 UTC, josetomas09 commented
Ha perdon!, le cambie el nombre al archivo tambien a "josetomas09" a eso te refieres?
Estoy bastante perdido, eh visto las reglas y el video de youtube pero no me sale, pido disculpas!
puedes cerrar el commit, no hay problema.
Saludos!!

2023-12-28 22:19 UTC, Roswell468 commented
> Ha perdon!, le cambie el nombre al archivo tambien a "josetomas09" a eso te refieres? Estoy bastante perdido, eh visto las reglas y el video de youtube pero no me sale, pido disculpas! puedes cerrar el commit, no hay problema. Saludos!!

No hay problema, rompiendo se aprende xD

Me refiero a que en este PR tienes 2 archivos:

![image](https://github.com/mouredev/roadmap-retos-programacion/assets/88008233/23a6e9b4-5ecd-41b9-8894-cf8d9c2e970b)

Además, el nombre de la carpeta java debe estar en minúsculas.

Si no estás muy familiarizado con Git, yo te recomendaría que guardes tu archivo fuera de tu repo local (para no perderlo), elimines las ramas que creaste, actualices tu fork (y pull) y vuelvas a empezar.
De esa manera ya tendrías la carpeta creada y solo tendrías que pegar tu solución en la carpeta java, hacer add, commit, push y crear la PR que solo te incluiría ese archivo.

Intenta y si no puedes lo seguimos viendo :)

Gracias.
Saludos!

2024-01-08 07:45 UTC, mouredev commented
Hola,

Se cierra PR por inactividad. Puedes enviar una nueva cuando quieras. Recuerda revisar reglas y comentarios.

Muchas gracias.

2024-01-08 07:45 UTC, closed without merging