Roadmap#00-01/javascript/ArticMoon.js
mouredev/roadmap-retos-programacion pull request #639
Opened 2024-01-09 22:54 UTC by FabianAPatinho

## Describe tus cambios
***(Opcional)*** *Sobre todo aconsejable si la "Pull Request" se corresponde con una corrección adicional y no con la presentación de un ejercicio.*

## Comprobaciones
Asegúrate de cumplir los siguientes puntos antes de realizar la "Pull Request":

- [x ] El título de mi Pull Request sigue este formato: "#[número] - [lenguaje_utilizado]". *(Ej: #00 - Python")*
- [x ] El nombre el fichero que se corresponde con el de mi usuario en GitHub más la extensión del lenguaje. *(Ej: mouredev.py)*
- [x ] El fichero de corrección se encuentra dentro del directorio del ejercicio y en una carpeta con el nombre del lenguaje de programación utilizado en minúsculas. *(Ej: 00/python/mouredev.py)*
- [x ] He revisado que el nombre del directorio del lenguaje no es conflictivo:
	- c#, no csharp
	- c++, no cplusplus
	- go, no golang
	- javascript, no js
- [x ] Únicamente he incluído los ficheros de ejercicios. No se aceptarán Pull Requests que contengan archivos adicionales asociados a editores de código o semejantes.

## Información

* Tienes toda la información sobre los retos semanales en [retosdeprogramacion.com/roadmap](https://retosdeprogramacion.com/roadmap).
* Cada semana se realizará la corrección en directo y publicación de un nuevo reto en [twitch.tv/mouredev](https://twitch.tv/mouredev).
* Recuerda que tienes un grupo de apoyo llamado "reto-semanal" en [Discord](https://discord.gg/mouredev).

2024-01-10 22:58 UTC, Roswell468 requested changes
Hola! Por favor revisa las [reglas](https://github.com/mouredev/roadmap-retos-programacion#instrucciones) de aportación de ejercicios.

- El nombre del fichero debe coincidir con el de tu usuario en GitHub más la extensión del lenguaje. (Ej: mouredev.py)

Gracias.
Saludos.

2024-01-11 00:05 UTC, ArticKun commented
Hola @Roswell468, creo que cambie mi nombre de usuario GitHub, y como subi dos ejercicios los puse en el titulo, entonces mejor subo el tercer ejercicio del roadmap ya nombrandolo como es, y hago la PR y no deberia haber ningun problema cierto? ... perdoname soy muy novato, estoy tambien aprendiendo git, y aun me enredo un poco , Gracias por la atención y paciencia

2024-01-11 00:14 UTC, Roswell468 commented
> Hola @Roswell468, creo que cambie mi nombre de usuario GitHub, y como subi dos ejercicios los puse en el titulo, entonces mejor subo el tercer ejercicio del roadmap ya nombrandolo como es, y hago la PR y no deberia haber ningun problema cierto? ... perdoname soy muy novato, estoy tambien aprendiendo git, y aun me enredo un poco , Gracias por la atención y paciencia

Hola! No te preocupes! Yo tampoco soy experto en git 😅 (suerte que sólo tengo que aprobar y no enviar PRs 😁)
Si renombras en tu repo los dos archivos y haces commit y push deberían actualizarse automáticamente los nombre en la PR.
Si quieres puedes hacer esto y además subir el tercer ejercicio. Si usas la misma rama todo va a quedar en esta PR sin necesidad que hagas otra.
Sino, renombralos, la apruebo y luego haces otra con la tercer solución, como prefieras o te sea más fácil.

2024-01-11 00:28 UTC, Roswell468 approved these changes

2024-01-11 00:28 UTC, merged