Reto00
mouredev/roadmap-retos-programacion pull request #64
Opened 2023-12-27 15:33 UTC by gliadev

## Describe tus cambios
***(Opcional)*** *Sobre todo aconsejable si la "Pull Request" se corresponde con una corrección adicional y no con la presentación de un ejercicio.*

## Comprobaciones
Asegúrate de cumplir los siguientes puntos antes de realizar la "Pull Request":

- [ ] El título de mi Pull Request sigue este formato: "#[número] - [lenguaje_utilizado]". *(Ej: #00 - Python")*
- [ ] El nombre el fichero que se corresponde con el de mi usuario en GitHub más la extensión del lenguaje. *(Ej: mouredev.py)*
- [ ] El fichero de corrección se encuentra dentro del directorio del ejercicio y en una carpeta con el nombre del lenguaje de programación utilizado en minúsculas. *(Ej: 00/python/mouredev.py)*
- [ ] He revisado que el nombre del directorio del lenguaje no es conflictivo:
	- c#, no csharp
	- c++, no cplusplus
	- go, no golang
	- javascript, no js
- [ ] Únicamente he incluído los ficheros de ejercicios. No se aceptarán Pull Requests que contengan archivos adicionales asociados a editores de código o semejantes.

## Información

* Tienes toda la información sobre los retos semanales en [retosdeprogramacion.com/roadmap](https://retosdeprogramacion.com/roadmap).
* Cada semana se realizará la corrección en directo y publicación de un nuevo reto en [twitch.tv/mouredev](https://twitch.tv/mouredev).
* Recuerda que tienes un grupo de apoyo llamado "reto-semanal" en [Discord](https://discord.gg/mouredev).

2023-12-27 20:29 UTC, kontroldev requested changes
Hola! Por favor revisa las [reglas](https://github.com/mouredev/retos-programacion-2023#c%C3%B3mo-puedo-participar) de aportación de ejercicios.

-No se aceptarán Pull Requests que contengan archivos adicionales asociados a editores de código o semejantes.
Gracias.

Saludos.

2023-12-27 20:50 UTC, gliadev commented
Hola Kontroldev soy blackhawk que estuvimos hablando anoche en "la cantina" pues me pierdo en principio pensé que lo había hecho bien, ya puedes perdonar en los PR estoy perdido, a ver si coincidimos de todas maneras lo voy a volver a intentar o que tengo que hacer??

2023-12-27 21:25 UTC, kontroldev commented
Si te ves muy liado, nos vemos algún dia en un grupo de estudio y nos compartes pantalla y te vamos guiando.

2023-12-28 06:56 UTC, gliadev commented
Pues me haces un favor de la leche te iba decir anoche pero me tuve que salir porque tenía que ir a recoger a la cria pero luego te aviso de la que me siento y te digo muchas gracias

2023-12-28 17:03 UTC, gliadev commented
Vuelvo a subirlo, espero a ver eliminado todo hecho un .gitignore y eliminado las carpetas a ver si lo saco gracias

2023-12-28 17:14 UTC, closed without merging