#04 - JavaScript
mouredev/roadmap-retos-programacion pull request #6632
Opened 2024-10-17 00:18 UTC by JuSeRDev

## Describe tus cambios
***(Opcional)*** *Sobre todo aconsejable si la "Pull Request" se corresponde con una corrección adicional y no con la presentación de un ejercicio.*

## Comprobaciones
Asegúrate de cumplir los siguientes puntos antes de realizar la "Pull Request":

- [ ] El título de mi Pull Request sigue este formato: "#[número] - [lenguaje_utilizado]". *(Ej: #00 - Python")*
- [ ] El nombre el fichero que se corresponde con el de mi usuario en GitHub más la extensión del lenguaje. *(Ej: mouredev.py)*
- [ ] El fichero de corrección se encuentra dentro del directorio del ejercicio y en una carpeta con el nombre del lenguaje de programación utilizado en minúsculas. *(Ej: 00/python/mouredev.py)*
- [ ] He revisado que el nombre del directorio del lenguaje no es conflictivo:
	- c#, no csharp
	- c++, no cplusplus
	- go, no golang
	- javascript, no js
- [ ] Únicamente he incluido los ficheros de ejercicios. No se aceptarán Pull Requests que contengan archivos adicionales asociados a editores de código o semejantes.

## Información

* Tienes toda la información sobre los retos semanales en [retosdeprogramacion.com/roadmap](https://retosdeprogramacion.com/roadmap).
* Cada semana se realizará la corrección en directo y publicación de un nuevo reto en [twitch.tv/mouredev](https://twitch.tv/mouredev).
* Recuerda que tienes un grupo de apoyo llamado "reto-semanal" en [Discord](https://discord.gg/mouredev).

2024-10-18 08:28 UTC, kontroldev requested changes
Hola! Por favor revisa las [reglas](https://github.com/mouredev/roadmap-retos-programacion#instrucciones) de aportación de ejercicios.

-No se aceptarán Pull Requests que contengan archivos adicionales asociados a editores de código o semejantes.

2024-10-19 14:56 UTC, JuSeRDev commented
Hola, mil disculpas es que soy nuevo en esto y no entiendo muy bien que fue lo que hice, pensé que solo había cargado el ejercicio 3 y 4 que no había podido cargar con anterioridad el ejercicio 3

2024-10-22 08:23 UTC, kontroldev commented
Buenas Juse, No te preocupes, yo era peor... 🫣
Si necesitas ayuda, miramos un dia de juntarnos en alguna sala en Discord y te digo como soluciónarlo.
No llevara 2 minutos.
Ya me dices que hacemos con esta PR.
-Miramos de solucionarlo, o la cerramos y creamos una nueva.

saludos. 👋

2024-10-23 03:26 UTC, JuSeRDev commented
De verdad sería de mucha ayuda, yo estoy en el discurso de mouredev, me encantaría poder recibir la ayuda porque intenté hacer algo más y no lo logré, comencé un repositorio nuevo para intentar hacer los retos porque no pude y no entendí como hacerlo.
Mi usuario es JuSeRDev

2024-10-30 10:56 UTC, kontroldev commented
Hola,

Cerramos PR por inactividad. Puedes enviar una nueva cuando quieras. Recuerda revisar reglas y comentarios.

Muchas gracias.

2024-10-30 10:56 UTC, closed without merging

2024-11-01 12:45 UTC, JuSeRDev commented
Dale, muchas gracias